DROP TABLE MEMBER;
DROP TABLE MEMBER_INFO;
DROP SEQUENCE SEQ_USER_NO;
-- DROP TABLE TRAINER_INFO;


-- 유저 테이블
CREATE TABLE MEMBER (
    USER_NO NUMBER NOT NULL CONSTRAINT PK_MEMBER PRIMARY KEY,  -- 회원번호
    USER_ID VARCHAR2(30) NOT NULL,  -- 회원아이디
    USER_PWD VARCHAR2(100) NOT NULL,  -- 회원비밀번호
    USER_NAME VARCHAR2(30) NOT NULL,  -- 회원이름
    EMAIL VARCHAR2(100) NOT NULL,  -- 이메일
    PHONE VARCHAR2(13),  -- 전화번호
    GENDER VARCHAR2(1),  -- 성별
    AGE NUMBER,  -- 나이
    ADDRESS VARCHAR2(100),  -- 주소
    ENROLL_DATE DATE DEFAULT SYSDATE,  -- 가입일
    USER_LEVEL NUMBER,  -- 1 트레이너, 2회원
    PT VARCHAR2(30),  -- 담당트레이너
    STATUS VARCHAR2(1) DEFAULT 'Y',  -- 상태 (Y, N)
    API VARCHAR2(100),  -- API 로그인 키
    QR VARCHAR2(300) NOT NULL,  -- QR코드 발급 후 저장 경로
    PROFILE_PIC VARCHAR2(300),  -- 회원 프로필 사진
    MEMBERSHIP VARCHAR2(30)  -- 회원이 소유한 회원권
);
COMMENT ON COLUMN MEMBER.USER_NO IS '회원번호';
COMMENT ON COLUMN MEMBER.USER_ID IS '회원아이디';
COMMENT ON COLUMN MEMBER.USER_PWD IS '회원비밀번호';
COMMENT ON COLUMN MEMBER.USER_NAME IS '회원이름';
COMMENT ON COLUMN MEMBER.EMAIL IS '이메일';
COMMENT ON COLUMN MEMBER.PHONE IS '전화번호';
COMMENT ON COLUMN MEMBER.GENDER IS '성별';
COMMENT ON COLUMN MEMBER.AGE IS '나이';
COMMENT ON COLUMN MEMBER.ADDRESS IS '주소';
COMMENT ON COLUMN MEMBER.ENROLL_DATE IS '가입일';
COMMENT ON COLUMN MEMBER.USER_LEVEL IS '1 트레이너, 2회원';
COMMENT ON COLUMN MEMBER.PT IS '담당트레이너';
COMMENT ON COLUMN MEMBER.STATUS IS 'Y, N';
COMMENT ON COLUMN MEMBER.API IS 'API 로그인 키';
COMMENT ON COLUMN MEMBER.QR IS 'QR코드 발급 후 저장 경로';
COMMENT ON COLUMN MEMBER.PROFILE_PIC IS '회원 프로필 사진';
COMMENT ON COLUMN MEMBER.MEMBERSHIP IS '회원이 소유한 회원권';

INSERT INTO MEMBER VALUES(1, 'test01', '1234', '실험맨', 'test@naver.com', '010-1111-1111', 'F', 11, '서울역', SYSDATE, 1, '이박사', 'Y', '임시api', '임시설정값', 'asdf/asd.png', '아무튼있음');

-- 유저 테이블 회원번호 시퀀스
CREATE SEQUENCE SEQ_USER_NO NOCACHE;

-- 회원추가정보 테이블
CREATE TABLE MEMBER_INFO(
    USER_INFO_NO NUMBER NOT NULL,
    USER_NO NUMBER NOT NULL, --회원번호
    HEIGHT NUMBER, --회원키
    WEIGHT NUMBER, --몸무게
    DISEASE VARCHAR2(100), --기저질환
    GOAL VARCHAR2(100), --운동목표
    CONSTRAINT PK_USER_INFO_NO PRIMARY KEY (USER_INFO_NO),
    CONSTRAINT FK_USER_NO FOREIGN KEY (USER_NO) REFERENCES MEMBER(USER_NO) ON DELETE CASCADE 
);
COMMENT ON COLUMN MEMBER_INFO.USER_NO IS '회원번호';
COMMENT ON COLUMN MEMBER_INFO.HEIGHT IS '회원키';
COMMENT ON COLUMN MEMBER_INFO.WEIGHT IS '몸무게';
COMMENT ON COLUMN MEMBER_INFO.DISEASE IS '기저질환';
COMMENT ON COLUMN MEMBER_INFO.GOAL IS '운동목표';


--CREATE TABLE TRAINER_INFO(
--    USER_NO NUMBER NOT NULL, --회원번호
--    TR_CAREER VARCHAR2(100), --트레이너경력
--    -- ㄴ> ERD에선 년수로 작성되어있고 노션에는 타입이 VARCHAR2로 되어있으니
--    --      서로 다른 뜻으로 작성 됐을 수도 있으므로 참고바람
--    TR_PROFILE VARCHAR2(300), --프로필사진(경로)
--    CONSTRAINT FK_USER_NO FOREIGN KEY (USER_NO) REFERENCES MEMBER(USER_NO) ON DELETE CASCADE 
--);
--COMMENT ON COLUMN TRAINER_INFO.USER_NO IS '회원번호';
--COMMENT ON COLUMN TRAINER_INFO.TR_CAREER IS '트레이너경력'; 
--COMMENT ON COLUMN TRAINER_INFO.TR_PROFILE IS '프로필사진';
